import type { VoiceCharacter } from '../packages/shared/types';

export const VOICE_CHARACTERS: VoiceCharacter[] = [
  {
    id: 'narrator',
    name: 'Storyteller',
    emoji: '\u{1F4D6}',
    description: 'Warm, captivating storyteller',
    pitch: 1.0,
    rate: 1.0,
    gradient: ['#FF6B6B', '#FF8E53'],
    isPremium: false,
    openaiVoice: 'nova',
  },
  {
    id: 'fairy',
    name: 'Fairy Sparkle',
    emoji: '\u{1F9DA}',
    description: 'Playful, bright and warm',
    pitch: 1.1,
    rate: 0.95,
    gradient: ['#C77DFF', '#E8A0FF'],
    isPremium: false,
    openaiVoice: 'shimmer',
  },
  {
    id: 'wizard',
    name: 'Old Wizard',
    emoji: '\u{1F9D9}',
    description: 'Wise, mature and balanced',
    pitch: 0.9,
    rate: 0.9,
    gradient: ['#1A1A6E', '#4A4AE0'],
    isPremium: true,
    openaiVoice: 'onyx',
  },
  {
    id: 'robot',
    name: 'Beep Bot',
    emoji: '\u{1F916}',
    description: 'Energetic and fun',
    pitch: 0.95,
    rate: 1.05,
    gradient: ['#00B4D8', '#48CAE4'],
    isPremium: true,
    openaiVoice: 'echo',
  },
  {
    id: 'pirate',
    name: 'Captain Arr',
    emoji: '\u{1F3F4}\u{200D}\u{2620}\u{FE0F}',
    description: 'Deep, confident adventurer',
    pitch: 0.9,
    rate: 0.95,
    gradient: ['#D4380D', '#FF7A45'],
    isPremium: true,
    openaiVoice: 'fable',
  },
  {
    id: 'princess',
    name: 'Princess Rose',
    emoji: '\u{1F478}',
    description: 'Sweet, gentle and clear',
    pitch: 1.1,
    rate: 0.95,
    gradient: ['#FF69B4', '#FFB6C1'],
    isPremium: true,
    openaiVoice: 'shimmer',
  },
  {
    id: 'dragon',
    name: 'Drago',
    emoji: '\u{1F432}',
    description: 'Deep, resonant and comforting',
    pitch: 0.85,
    rate: 1.0,
    gradient: ['#52B788', '#95D5B2'],
    isPremium: true,
    openaiVoice: 'onyx',
  },
  {
    id: 'alien',
    name: 'Zibzob',
    emoji: '\u{1F47D}',
    description: 'Quirky, husky trickster',
    pitch: 1.15,
    rate: 1.05,
    gradient: ['#A8E6CF', '#DCEDC1'],
    isPremium: true,
    openaiVoice: 'alloy',
  },
];

export function getVoiceCharacterById(id: string): VoiceCharacter | undefined {
  return VOICE_CHARACTERS.find(v => v.id === id);
}
