import type { Theme, Character, AgeGroup, AgeGroupConfig } from '../../../packages/shared/types';

export const THEMES: Theme[] = [
  {
    id: 'space',
    name: 'Space Adventure',
    nameKey: 'themeSpace',
    emoji: '🚀',
    gradient: ['#2C3E50', '#4CA1AF'],
    description: 'Blast off to the stars!',
    descKey: 'themeSpaceDesc',
  },
  {
    id: 'ocean',
    name: 'Ocean Discovery',
    nameKey: 'themeOcean',
    emoji: '🌊',
    gradient: ['#0077B6', '#00B4D8'],
    description: 'Dive into the deep blue sea!',
    descKey: 'themeOceanDesc',
  },
  {
    id: 'forest',
    name: 'Enchanted Forest',
    nameKey: 'themeForest',
    emoji: '🌳',
    gradient: ['#2D6A4F', '#52B788'],
    description: 'Explore magical woodlands!',
    descKey: 'themeForestDesc',
  },
  {
    id: 'castle',
    name: 'Royal Castle',
    nameKey: 'themeCastle',
    emoji: '🏰',
    gradient: ['#7B2D8E', '#C77DFF'],
    description: 'Enter a kingdom of wonder!',
    descKey: 'themeCastleDesc',
  },
  {
    id: 'dinosaur',
    name: 'Dinosaur World',
    nameKey: 'themeDinosaur',
    emoji: '🦕',
    gradient: ['#BC6C25', '#DDA15E'],
    description: 'Travel back in time!',
    descKey: 'themeDinosaurDesc',
  },
  {
    id: 'fairy',
    name: 'Fairy Garden',
    nameKey: 'themeFairy',
    emoji: '🧚',
    gradient: ['#FF69B4', '#FFB6C1'],
    description: 'Enter a world of tiny magic!',
    descKey: 'themeFairyDesc',
  },
  {
    id: 'pirate',
    name: 'Pirate Treasure',
    nameKey: 'themePirate',
    emoji: '🏴‍☠️',
    gradient: ['#8B4513', '#DAA520'],
    description: 'Set sail for adventure!',
    descKey: 'themePirateDesc',
  },
  {
    id: 'robot',
    name: 'Robot City',
    nameKey: 'themeRobot',
    emoji: '🤖',
    gradient: ['#4A4E69', '#9A8C98'],
    description: 'Build and create in the future!',
    descKey: 'themeRobotDesc',
  },
  {
    id: 'animal',
    name: 'Animal Kingdom',
    nameKey: 'themeAnimal',
    emoji: '🦁',
    gradient: ['#F4A261', '#E76F51'],
    description: 'Meet amazing animal friends!',
    descKey: 'themeAnimalDesc',
  },
  {
    id: 'superhero',
    name: 'Superhero Academy',
    nameKey: 'themeSuperhero',
    emoji: '🦸',
    gradient: ['#E63946', '#457B9D'],
    description: 'Discover your superpowers!',
    descKey: 'themeSuperheroDesc',
  },
];

export const CHARACTERS: Character[] = [
  // Magical Creatures
  {
    id: 'stardust',
    name: 'Stardust',
    emoji: '🦄',
    trait: 'Magical Unicorn',
    traitKey: 'charStardustTrait',
    description: 'A shimmering unicorn whose rainbow mane glows when she makes a wish — but each wish must be earned through kindness',
  },
  {
    id: 'spark',
    name: 'Spark',
    emoji: '🐉',
    trait: 'Baby Dragon',
    traitKey: 'charSparkTrait',
    description: 'A tiny dragon who sneezes confetti instead of fire and desperately wants to learn to fly before the Dragon Festival',
  },
  {
    id: 'coral',
    name: 'Coral',
    emoji: '🧜‍♀️',
    trait: 'Little Mermaid',
    traitKey: 'charCoralTrait',
    description: 'A curious mermaid who collects human treasures in her underwater cave and dreams of seeing snow for the first time',
  },
  {
    id: 'iris',
    name: 'Iris',
    emoji: '🧚',
    trait: 'Garden Fairy',
    traitKey: 'charIrisTrait',
    description: 'A tiny fairy who lives inside a sunflower and can make any plant grow, but her magic goes hilariously wrong when she sneezes',
  },
  // Brave Kids
  {
    id: 'luna',
    name: 'Luna',
    emoji: '👧',
    trait: 'Stargazer Girl',
    traitKey: 'charLunaTrait',
    description: 'A girl who talks to the moon every night and one day receives a mysterious map that leads to the place where stars are born',
  },
  {
    id: 'kai',
    name: 'Kai',
    emoji: '👦',
    trait: 'Inventor Boy',
    traitKey: 'charKaiTrait',
    description: 'A boy who builds amazing inventions from things he finds in his recycling bin — his latest creation might just save the day',
  },
  {
    id: 'nova',
    name: 'Nova',
    emoji: '🦸‍♀️',
    trait: 'Tiny Superhero',
    traitKey: 'charNovaTrait',
    description: 'An ordinary kid who discovers a magical cape in her grandmother\'s attic — it gives her one superpower each day, but she never knows which one',
  },
  // Animal Friends
  {
    id: 'biscuit',
    name: 'Biscuit',
    emoji: '🐶',
    trait: 'Adventurous Puppy',
    traitKey: 'charBiscuitTrait',
    description: 'A golden puppy with one floppy ear who follows interesting smells into the most extraordinary adventures',
  },
  {
    id: 'mochi',
    name: 'Mochi',
    emoji: '🐱',
    trait: 'Clever Kitten',
    traitKey: 'charMochiTrait',
    description: 'A fluffy kitten who can read books and secretly helps the neighborhood kids with their homework through the window',
  },
  {
    id: 'clover',
    name: 'Clover',
    emoji: '🐰',
    trait: 'Brave Bunny',
    traitKey: 'charCloverTrait',
    description: 'The smallest bunny in the warren who proves that the biggest heart matters more than the biggest ears',
  },
  {
    id: 'rex',
    name: 'Rex',
    emoji: '🦖',
    trait: 'Friendly Dinosaur',
    traitKey: 'charRexTrait',
    description: 'A vegetarian T-Rex who is gentle as a lamb and uses his enormous size to help all the smaller animals in Dino Valley',
  },
  // Fantasy & Fun
  {
    id: 'beep',
    name: 'Beep',
    emoji: '🤖',
    trait: 'Curious Robot',
    traitKey: 'charBeepTrait',
    description: 'A little robot who was built to clean but wants to learn about feelings — especially this strange thing humans call "laughter"',
  },
  {
    id: 'captain-finn',
    name: 'Captain Finn',
    emoji: '🏴‍☠️',
    trait: 'Kid Pirate',
    traitKey: 'charFinnTrait',
    description: 'A seven-year-old pirate captain who sails a ship made of cardboard boxes and discovers treasures that money can\'t buy',
  },
  {
    id: 'honey',
    name: 'Honey',
    emoji: '🐻',
    trait: 'Cuddly Bear Cub',
    traitKey: 'charHoneyTrait',
    description: 'A bear cub who gives the warmest hugs in the forest and is determined to stay awake for her very first winter to see snow',
  },
  {
    id: 'zorp',
    name: 'Zorp',
    emoji: '👽',
    trait: 'Friendly Alien',
    traitKey: 'charZorpTrait',
    description: 'A purple alien visiting Earth for a school project who is baffled by pizza, rain, and why humans keep fluffy creatures called "dogs" in their houses',
  },
];

export const AGE_GROUPS: Record<AgeGroup, AgeGroupConfig> = {
  '3-5': {
    label: '3-5 Years',
    pages: 6,
    maxWordsPerPage: 50,
    description: 'Simple words, big pictures',
  },
  '5-7': {
    label: '5-7 Years',
    pages: 10,
    maxWordsPerPage: 80,
    description: 'Fun adventures with richer stories',
  },
  '7-10': {
    label: '7-10 Years',
    pages: 12,
    maxWordsPerPage: 120,
    description: 'Deeper tales with rich characters',
  },
};

export const SUBSCRIPTION_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: '$0',
    period: 'forever',
    features: ['2 stories per day', 'Basic themes', 'Standard illustrations'],
  },
  {
    id: 'storypal_monthly',
    name: 'Monthly',
    price: '$4.99',
    period: 'month',
    features: ['Unlimited stories', 'All themes & characters', 'HD illustrations', 'Save & share'],
  },
  {
    id: 'storypal_yearly',
    name: 'Yearly',
    price: '$29.99',
    period: 'year',
    features: ['Unlimited stories', 'All themes & characters', 'HD illustrations', 'Save & share', 'Priority generation'],
    isPopular: true,
  },
  {
    id: 'storypal_lifetime',
    name: 'Lifetime',
    price: '$59.99',
    period: 'once',
    features: ['Everything in Yearly', 'One-time payment', 'Future updates included'],
  },
];
